### ISSUE TITLE
Keeps looping

### ISSUE THREAD

**Issue by Dulanic** [mvisonneau/docker-generatedata#3] opened 2018-09-16 16:28 UTC
I love the idea of this as a docker container. However, mine keeps looping through the 3 steps;

```

sudo   docker run -it -p 8000:80 \
     -e GD_DB_HOSTNAME="192.168.2.155, 1433" \
     -e GD_DB_NAME=generatedata \
     -e GD_DB_USERNAME=user \
     -e GD_DB_PASSWORD=password \
     mvisonneau/generatedata
```

```

ing environment variables

entrypoint.sh: line 4: test: 192.168.2.155,: unary operator expected

guring application

16T16:23:18Z af5c5731f80c /usr/local/bin/confd[7]: INFO Backend set to env

16T16:23:18Z af5c5731f80c /usr/local/bin/confd[7]: INFO Starting confd

16T16:23:18Z af5c5731f80c /usr/local/bin/confd[7]: INFO Backend source(s) set to 

16T16:23:18Z af5c5731f80c /usr/local/bin/confd[7]: INFO Target config /opt/generatedata/settings.php out of sync

16T16:23:18Z af5c5731f80c /usr/local/bin/confd[7]: INFO Target config /opt/generatedata/settings.php has been updated

ing php-fpm and nginx

16 16:23:18,850 CRIT Set uid to user 0

16 16:23:18,852 INFO supervisord started with pid 15

16 16:23:19,854 INFO spawned: 'nginx' with pid 18

16 16:23:19,855 INFO spawned: 'php-fpm' with pid 19

2018 16:23:19] NOTICE: fpm is running, pid 19

2018 16:23:19] NOTICE: ready to handle connections

16 16:23:20,882 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

16 16:23:20,891 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

1 -  16/Sep/2018:16:23:31 +0000 "GET /index.php" 302

2.128 - - [16/Sep/2018:16:23:31 +0000] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.117 0.117 . -

1 -  16/Sep/2018:16:23:31 +0000 "GET /install.php" 200

2.128 - - [16/Sep/2018:16:23:32 +0000] "GET /install.php HTTP/1.1" 200 13057 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.073 0.073 . -

1 -  16/Sep/2018:16:23:32 +0000 "GET /resources/scripts/lang.php" 200

2.128 - - [16/Sep/2018:16:23:32 +0000] "GET /resources/scripts/lang.php?.js HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.087 0.087 . -

1 -  16/Sep/2018:16:23:32 +0000 "GET /resources/scripts/constants.php" 200

2.128 - - [16/Sep/2018:16:23:32 +0000] "GET /resources/scripts/constants.php?.js HTTP/1.1" 200 2867 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.265 0.265 . -

1 -  16/Sep/2018:16:23:32 +0000 "GET /resources/scripts/lang.php" 200

2.128 - - [16/Sep/2018:16:23:32 +0000] "GET /resources/scripts/lang.php?lang=en HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.087 0.087 . -

2018 16:23:34] WARNING: [pool www] child 22 said into stderr: "sendmail: can't connect to remote host (127.0.0.1): Connection refused"

1 -  16/Sep/2018:16:23:34 +0000 "POST /ajax.php" 200

2.128 - - [16/Sep/2018:16:23:34 +0000] "POST /ajax.php HTTP/1.1" 200 37 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.075 0.075 . -

1 -  16/Sep/2018:16:23:35 +0000 "POST /ajax.php" 200

2.128 - - [16/Sep/2018:16:23:35 +0000] "POST /ajax.php HTTP/1.1" 200 6220 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.156 0.156 . -

1 -  16/Sep/2018:16:23:35 +0000 "POST /ajax.php" 200

2.128 - - [16/Sep/2018:16:23:36 +0000] "POST /ajax.php HTTP/1.1" 200 345 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.088 0.088 . -

1 -  16/Sep/2018:16:23:36 +0000 "POST /ajax.php" 200

2.128 - - [16/Sep/2018:16:23:36 +0000] "POST /ajax.php HTTP/1.1" 200 860 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.090 0.090 . -

1 -  16/Sep/2018:16:23:39 +0000 "POST /ajax.php" 200

2.128 - - [16/Sep/2018:16:23:39 +0000] "POST /ajax.php HTTP/1.1" 200 128 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.075 0.074 . -

1 -  16/Sep/2018:16:23:41 +0000 "GET /index.php" 302

2.128 - - [16/Sep/2018:16:23:41 +0000] "GET / HTTP/1.1" 302 5 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.090 0.090 . -

1 -  16/Sep/2018:16:23:41 +0000 "GET /install.php" 200

2.128 - - [16/Sep/2018:16:23:41 +0000] "GET /install.php HTTP/1.1" 200 13051 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.030 0.030 . -

1 -  16/Sep/2018:16:23:41 +0000 "GET /resources/scripts/lang.php" 200

2.128 - - [16/Sep/2018:16:23:41 +0000] "GET /resources/scripts/lang.php?.js HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.082 0.082 . -

1 -  16/Sep/2018:16:23:41 +0000 "GET /resources/scripts/constants.php" 200

2.128 - - [16/Sep/2018:16:23:42 +0000] "GET /resources/scripts/constants.php?.js HTTP/1.1" 200 2867 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.220 0.220 . -

1 -  16/Sep/2018:16:23:42 +0000 "GET /resources/scripts/lang.php" 200

2.128 - - [16/Sep/2018:16:23:42 +0000] "GET /resources/scripts/lang.php?lang=en HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0" "-" 0.075 0.075 . 
```

**Comment by mvisonneau** [comment] 2018-09-16 21:45
👋 isn't there something odd with your `GD_DB_HOSTNAME` value ? 🤔

**Comment by Dulanic** [comment] 2018-09-17 10:50
Not that I know of, that;s how I connect using SSMS. I tried that without the "" but that didnt work either. I use a specific port to connect. I also tried /w just 192.168.2.155. This isnt a external site so I have no host name. I'd use localhost, but that tends to be an issue /w docker since docker containers have their own IPs.

**Comment by Dulanic** [comment] 2018-09-17 10:58
I've tried it as localhost, 192.168.2.155, server, etc... none work.

```
dulanic@server:~$ sudo   docker run -it -p 8000:80      -e GD_DB_HOSTNAME=192.168.2.155      -e GD_DB_NAME=generatedata      -e GD_DB_USERNAME=user -e GD_DB_PASSWORD=pass mvisonneau/generatedata
-> checking environment variables
-> configuring application
2018-09-17T10:53:55Z 7354231d2c3b /usr/local/bin/confd[8]: INFO Backend set to env
2018-09-17T10:53:55Z 7354231d2c3b /usr/local/bin/confd[8]: INFO Starting confd
2018-09-17T10:53:55Z 7354231d2c3b /usr/local/bin/confd[8]: INFO Backend source(s) set to
2018-09-17T10:53:55Z 7354231d2c3b /usr/local/bin/confd[8]: INFO Target config /opt/generatedata/settings.php out of sync
2018-09-17T10:53:55Z 7354231d2c3b /usr/local/bin/confd[8]: INFO Target config /opt/generatedata/settings.php has been updated
-> starting php-fpm and nginx
2018-09-17 10:53:55,348 CRIT Set uid to user 0
2018-09-17 10:53:55,349 INFO supervisord started with pid 15
2018-09-17 10:53:56,351 INFO spawned: 'nginx' with pid 18
2018-09-17 10:53:56,352 INFO spawned: 'php-fpm' with pid 19
[17-Sep-2018 10:53:56] NOTICE: fpm is running, pid 19
[17-Sep-2018 10:53:56] NOTICE: ready to handle connections
2018-09-17 10:53:57,381 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-17 10:53:57,381 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
127.0.0.1 -  17/Sep/2018:10:54:04 +0000 "GET /index.php" 302
192.168.2.7 - - [17/Sep/2018:10:54:05 +0000] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.089 0.089 . -
127.0.0.1 -  17/Sep/2018:10:54:05 +0000 "GET /install.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:05 +0000] "GET /install.php HTTP/1.1" 200 13051 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.154 0.154 . -
127.0.0.1 -  17/Sep/2018:10:54:05 +0000 "GET /resources/scripts/constants.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:05 +0000] "GET /resources/scripts/constants.php?.js HTTP/1.1" 200 2867 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.019 0.019 . -
127.0.0.1 -  17/Sep/2018:10:54:05 +0000 "GET /resources/scripts/lang.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:05 +0000] "GET /resources/scripts/lang.php?.js HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.125 0.125 . -
127.0.0.1 -  17/Sep/2018:10:54:05 +0000 "GET /resources/scripts/lang.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:05 +0000] "GET /resources/scripts/lang.php?lang=en HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.016 0.016 . -
[17-Sep-2018 10:54:06] WARNING: [pool www] child 21 said into stderr: "sendmail: can't connect to remote host (127.0.0.1): Connection refused"
127.0.0.1 -  17/Sep/2018:10:54:06 +0000 "POST /ajax.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:06 +0000] "POST /ajax.php HTTP/1.1" 200 37 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.096 0.096 . -
127.0.0.1 -  17/Sep/2018:10:54:08 +0000 "POST /ajax.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:08 +0000] "POST /ajax.php HTTP/1.1" 200 6220 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.123 0.123 . -
127.0.0.1 -  17/Sep/2018:10:54:08 +0000 "POST /ajax.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:08 +0000] "POST /ajax.php HTTP/1.1" 200 345 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.115 0.115 . -
127.0.0.1 -  17/Sep/2018:10:54:08 +0000 "POST /ajax.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:08 +0000] "POST /ajax.php HTTP/1.1" 200 860 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.033 0.033 . -
127.0.0.1 -  17/Sep/2018:10:54:10 +0000 "POST /ajax.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:10 +0000] "POST /ajax.php HTTP/1.1" 200 128 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.024 0.024 . -
127.0.0.1 -  17/Sep/2018:10:54:11 +0000 "GET /index.php" 302
192.168.2.7 - - [17/Sep/2018:10:54:11 +0000] "GET / HTTP/1.1" 302 5 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.017 0.017 . -
127.0.0.1 -  17/Sep/2018:10:54:11 +0000 "GET /install.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:11 +0000] "GET /install.php HTTP/1.1" 200 13051 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.015 0.015 . -
127.0.0.1 -  17/Sep/2018:10:54:12 +0000 "GET /resources/scripts/lang.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:12 +0000] "GET /resources/scripts/lang.php?.js HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.019 0.019 . -
127.0.0.1 -  17/Sep/2018:10:54:12 +0000 "GET /resources/scripts/constants.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:12 +0000] "GET /resources/scripts/constants.php?.js HTTP/1.1" 200 2867 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.019 0.019 . -
127.0.0.1 -  17/Sep/2018:10:54:12 +0000 "GET /resources/scripts/lang.php" 200
192.168.2.7 - - [17/Sep/2018:10:54:12 +0000] "GET /resources/scripts/lang.php?lang=en HTTP/1.1" 200 18420 "http://192.168.2.155:8000/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-" 0.017 0.017 . -

```

**Comment by mvisonneau** [comment] 2019-04-03 13:18
I have rechecked myself and managed to get it to work fine with basic docker configuration. I believe the issue is not related to the image it self but to network/database connectivity/configuration. Closing it.

**Closed as completed by mvisonneau** 2019-04-03 13:18 UTC
